services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: .
    container_name: api
    depends_on:
      - mongo
    ports:
      - "503:503"

volumes:
  mongo_data: